# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frontend\ApplicationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ApplicationWindow(object):
    def setupUi(self, ApplicationWindow):
        ApplicationWindow.setObjectName("ApplicationWindow")
        ApplicationWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(ApplicationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.videoPlayer = VideoPlayer(self.centralwidget)
        self.videoPlayer.setGeometry(QtCore.QRect(400, 10, 1024, 768))
        self.videoPlayer.setObjectName("videoPlayer")
        self.comboCameraSelect = QtWidgets.QComboBox(self.videoPlayer)
        self.comboCameraSelect.setGeometry(QtCore.QRect(10, 10, 111, 22))
        self.comboCameraSelect.setEditable(False)
        self.comboCameraSelect.setMaxVisibleItems(2)
        self.comboCameraSelect.setObjectName("comboCameraSelect")
        self.comboCameraSelect.addItem("")
        self.comboCameraSelect.addItem("")
        self.autoButton = AutoButton(self.centralwidget)
        self.autoButton.setGeometry(QtCore.QRect(145, 350, 111, 51))
        self.autoButton.setObjectName("autoButton")
        self.buttonPickSample = QtWidgets.QPushButton(self.centralwidget)
        self.buttonPickSample.setGeometry(QtCore.QRect(580, 810, 181, 81))
        self.buttonPickSample.setObjectName("buttonPickSample")
        self.buttonRetSample = QtWidgets.QPushButton(self.centralwidget)
        self.buttonRetSample.setGeometry(QtCore.QRect(1070, 810, 181, 81))
        self.buttonRetSample.setObjectName("buttonRetSample")
        self.labelJoystick = QtWidgets.QLabel(self.centralwidget)
        self.labelJoystick.setGeometry(QtCore.QRect(1620, 170, 161, 61))
        self.labelJoystick.setAlignment(QtCore.Qt.AlignCenter)
        self.labelJoystick.setObjectName("labelJoystick")
        self.labelX = QtWidgets.QLabel(self.centralwidget)
        self.labelX.setGeometry(QtCore.QRect(1620, 259, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelX.setFont(font)
        self.labelX.setObjectName("labelX")
        self.labelY = QtWidgets.QLabel(self.centralwidget)
        self.labelY.setGeometry(QtCore.QRect(1620, 290, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelY.setFont(font)
        self.labelY.setObjectName("labelY")
        self.lcdNumberX = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumberX.setGeometry(QtCore.QRect(1710, 260, 61, 23))
        self.lcdNumberX.setObjectName("lcdNumberX")
        self.lcdNumberY = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumberY.setGeometry(QtCore.QRect(1710, 290, 61, 23))
        self.lcdNumberY.setObjectName("lcdNumberY")
        self.labelLogo = QtWidgets.QLabel(self.centralwidget)
        self.labelLogo.setGeometry(QtCore.QRect(60, 40, 281, 281))
        self.labelLogo.setObjectName("labelLogo")
        ApplicationWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ApplicationWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        ApplicationWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ApplicationWindow)
        self.statusbar.setObjectName("statusbar")
        ApplicationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ApplicationWindow)
        self.comboCameraSelect.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ApplicationWindow)

    def retranslateUi(self, ApplicationWindow):
        _translate = QtCore.QCoreApplication.translate
        ApplicationWindow.setWindowTitle(_translate("ApplicationWindow", "Micro Manipulation"))
        self.comboCameraSelect.setItemText(0, _translate("ApplicationWindow", "Camera1"))
        self.comboCameraSelect.setItemText(1, _translate("ApplicationWindow", "Camera2"))
        self.buttonPickSample.setText(_translate("ApplicationWindow", "Pick a Sample"))
        self.buttonRetSample.setText(_translate("ApplicationWindow", "Return the Sample"))
        self.labelJoystick.setText(_translate("ApplicationWindow", "Joystick not active"))
        self.labelX.setText(_translate("ApplicationWindow", "x position:"))
        self.labelY.setText(_translate("ApplicationWindow", "y position:"))
        self.labelLogo.setText(_translate("ApplicationWindow", "Image"))
from frontend.VideoPlayer import VideoPlayer
from frontend.customWidgets import AutoButton


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ApplicationWindow = QtWidgets.QMainWindow()
    ui = Ui_ApplicationWindow()
    ui.setupUi(ApplicationWindow)
    ApplicationWindow.show()
    sys.exit(app.exec_())
